/**
 * Aether TypeScript/JavaScript bindings
 * 
 * This module provides a high-level TypeScript/JavaScript API for the Aether DSL.
 * It wraps the WebAssembly implementation generated by wasm-pack.
 * 
 * @packageDocumentation
 */

/**
 * Aether value types that can be returned from evaluation
 */
export type AetherValue =
    | number
    | string
    | boolean
    | AetherValue[]
    | { [key: string]: AetherValue }
    | null;

/**
 * Main Aether engine class
 * 
 * @example
 * ```typescript
 * import { Aether } from '@xiaozuhui/aether';
 * 
 * async function main() {
 *   const engine = await Aether.create();
 *   
 *   const result = engine.eval(`
 *     Set X 10
 *     Set Y 20
 *     (X + Y)
 *   `);
 *   
 *   console.log(result); // 30
 * }
 * ```
 */
export class Aether {
    private wasmModule: any = null;
    private engine: any = null;
    private initialized = false;

    private constructor() { }

    /**
     * Create and initialize a new Aether engine
     * 
     * @returns A promise that resolves to an initialized Aether instance
     * 
     * @example
     * ```typescript
     * const engine = await Aether.create();
     * ```
     */
    static async create(): Promise<Aether> {
        const instance = new Aether();
        await instance.init();
        return instance;
    }

    /**
     * Create and initialize a new Aether engine with all IO permissions enabled
     * 
     * Warning: Only use this when you trust the scripts being executed.
     * 
     * @returns A promise that resolves to an initialized Aether instance
     * 
     * @example
     * ```typescript
     * const engine = await Aether.createWithPermissions();
     * ```
     */
    static async createWithPermissions(): Promise<Aether> {
        const instance = new Aether();
        await instance.init(true);
        return instance;
    }

    /**
     * Initialize the WASM module
     * 
     * @internal
     */
    private async init(withPermissions: boolean = false): Promise<void> {
        if (this.initialized) {
            return;
        }

        try {
            // In a real implementation, this would load the WASM module
            // For now, we'll use a placeholder
            this.wasmModule = await import('../pkg/aether_wasm');

            if (withPermissions) {
                this.engine = this.wasmModule.Aether.newWithPermissions();
            } else {
                this.engine = new this.wasmModule.Aether();
            }

            this.initialized = true;
        } catch (error) {
            throw new Error(`Failed to initialize Aether: ${error}`);
        }
    }

    /**
     * Evaluate Aether code and return the result
     * 
     * @param code - The Aether code to evaluate
     * @returns The result of the evaluation
     * @throws Error if the code fails to parse or encounters a runtime error
     * 
     * @example
     * ```typescript
     * const result = engine.eval('Set X 10\n(X + 20)');
     * console.log(result); // 30
     * ```
     */
    eval(code: string): AetherValue {
        if (!this.initialized || !this.engine) {
            throw new Error('Aether not initialized. Call Aether.create() first.');
        }

        try {
            return this.engine.eval(code);
        } catch (error) {
            throw new Error(`Evaluation error: ${error}`);
        }
    }

    /**
     * Get the version of the Aether engine
     * 
     * @returns The version string
     */
    static version(): string {
        // This would normally call the WASM function
        return '0.1.0';
    }
}

/**
 * Convenience function to evaluate Aether code without creating an engine instance
 * 
 * Note: This creates a new engine for each call, which may be inefficient
 * for multiple evaluations. Consider using Aether.create() for better performance.
 * 
 * @param code - The Aether code to evaluate
 * @returns A promise that resolves to the evaluation result
 * 
 * @example
 * ```typescript
 * const result = await eval('(10 + 20)');
 * console.log(result); // 30
 * ```
 */
export async function evalCode(code: string): Promise<AetherValue> {
    const engine = await Aether.create();
    return engine.eval(code);
}

// Re-export types
export type { AetherValue as Value };
